import regions from "./data/china-cities.json";
import type { Place } from "./types";

export type City = Place & { region: string };

export const CITIES: City[] = [
  {
    name: "北京",
    region: "北京",
    longitude: 116.41,
    latitude: 39.9,
    timezone: 8,
  },
  {
    name: "天津",
    region: "天津",
    longitude: 117.2,
    latitude: 39.13,
    timezone: 8,
  },
  {
    name: "上海",
    region: "上海",
    longitude: 121.47,
    latitude: 31.23,
    timezone: 8,
  },
  {
    name: "重庆",
    region: "重庆",
    longitude: 106.55,
    latitude: 29.56,
    timezone: 8,
  },
  {
    name: "广州",
    region: "广东",
    longitude: 113.26,
    latitude: 23.13,
    timezone: 8,
  },
  {
    name: "深圳",
    region: "广东",
    longitude: 114.06,
    latitude: 22.54,
    timezone: 8,
  },
  {
    name: "珠海",
    region: "广东",
    longitude: 113.58,
    latitude: 22.27,
    timezone: 8,
  },
  {
    name: "佛山",
    region: "广东",
    longitude: 113.12,
    latitude: 23.02,
    timezone: 8,
  },
  {
    name: "东莞",
    region: "广东",
    longitude: 113.75,
    latitude: 23.05,
    timezone: 8,
  },
  {
    name: "汕头",
    region: "广东",
    longitude: 116.68,
    latitude: 23.35,
    timezone: 8,
  },
  {
    name: "成都",
    region: "四川",
    longitude: 104.07,
    latitude: 30.67,
    timezone: 8,
  },
  {
    name: "绵阳",
    region: "四川",
    longitude: 104.68,
    latitude: 31.47,
    timezone: 8,
  },
  {
    name: "杭州",
    region: "浙江",
    longitude: 120.16,
    latitude: 30.25,
    timezone: 8,
  },
  {
    name: "宁波",
    region: "浙江",
    longitude: 121.55,
    latitude: 29.87,
    timezone: 8,
  },
  {
    name: "温州",
    region: "浙江",
    longitude: 120.7,
    latitude: 28.0,
    timezone: 8,
  },
  {
    name: "南京",
    region: "江苏",
    longitude: 118.8,
    latitude: 32.06,
    timezone: 8,
  },
  {
    name: "苏州",
    region: "江苏",
    longitude: 120.62,
    latitude: 31.3,
    timezone: 8,
  },
  {
    name: "无锡",
    region: "江苏",
    longitude: 120.3,
    latitude: 31.57,
    timezone: 8,
  },
  {
    name: "武汉",
    region: "湖北",
    longitude: 114.31,
    latitude: 30.59,
    timezone: 8,
  },
  {
    name: "长沙",
    region: "湖南",
    longitude: 112.94,
    latitude: 28.23,
    timezone: 8,
  },
  {
    name: "郑州",
    region: "河南",
    longitude: 113.63,
    latitude: 34.75,
    timezone: 8,
  },
  {
    name: "西安",
    region: "陕西",
    longitude: 108.94,
    latitude: 34.34,
    timezone: 8,
  },
  {
    name: "济南",
    region: "山东",
    longitude: 117.0,
    latitude: 36.65,
    timezone: 8,
  },
  {
    name: "青岛",
    region: "山东",
    longitude: 120.38,
    latitude: 36.07,
    timezone: 8,
  },
  {
    name: "合肥",
    region: "安徽",
    longitude: 117.23,
    latitude: 31.82,
    timezone: 8,
  },
  {
    name: "福州",
    region: "福建",
    longitude: 119.3,
    latitude: 26.08,
    timezone: 8,
  },
  {
    name: "厦门",
    region: "福建",
    longitude: 118.09,
    latitude: 24.48,
    timezone: 8,
  },
  {
    name: "南昌",
    region: "江西",
    longitude: 115.86,
    latitude: 28.68,
    timezone: 8,
  },
  {
    name: "沈阳",
    region: "辽宁",
    longitude: 123.43,
    latitude: 41.8,
    timezone: 8,
  },
  {
    name: "大连",
    region: "辽宁",
    longitude: 121.61,
    latitude: 38.91,
    timezone: 8,
  },
  {
    name: "长春",
    region: "吉林",
    longitude: 125.32,
    latitude: 43.82,
    timezone: 8,
  },
  {
    name: "哈尔滨",
    region: "黑龙江",
    longitude: 126.53,
    latitude: 45.8,
    timezone: 8,
  },
  {
    name: "石家庄",
    region: "河北",
    longitude: 114.51,
    latitude: 38.04,
    timezone: 8,
  },
  {
    name: "太原",
    region: "山西",
    longitude: 112.55,
    latitude: 37.87,
    timezone: 8,
  },
  {
    name: "昆明",
    region: "云南",
    longitude: 102.83,
    latitude: 24.88,
    timezone: 8,
  },
  {
    name: "大理",
    region: "云南",
    longitude: 100.27,
    latitude: 25.61,
    timezone: 8,
  },
  {
    name: "贵阳",
    region: "贵州",
    longitude: 106.63,
    latitude: 26.65,
    timezone: 8,
  },
  {
    name: "南宁",
    region: "广西",
    longitude: 108.37,
    latitude: 22.82,
    timezone: 8,
  },
  {
    name: "海口",
    region: "海南",
    longitude: 110.32,
    latitude: 20.04,
    timezone: 8,
  },
  {
    name: "三亚",
    region: "海南",
    longitude: 109.51,
    latitude: 18.25,
    timezone: 8,
  },
  {
    name: "兰州",
    region: "甘肃",
    longitude: 103.83,
    latitude: 36.06,
    timezone: 8,
  },
  {
    name: "西宁",
    region: "青海",
    longitude: 101.78,
    latitude: 36.62,
    timezone: 8,
  },
  {
    name: "银川",
    region: "宁夏",
    longitude: 106.23,
    latitude: 38.49,
    timezone: 8,
  },
  {
    name: "呼和浩特",
    region: "内蒙古",
    longitude: 111.75,
    latitude: 40.84,
    timezone: 8,
  },
  {
    name: "乌鲁木齐",
    region: "新疆",
    longitude: 87.62,
    latitude: 43.83,
    timezone: 8,
  },
  {
    name: "喀什",
    region: "新疆",
    longitude: 75.99,
    latitude: 39.47,
    timezone: 8,
  },
  {
    name: "拉萨",
    region: "西藏",
    longitude: 91.11,
    latitude: 29.65,
    timezone: 8,
  },
  {
    name: "香港",
    region: "香港",
    longitude: 114.17,
    latitude: 22.32,
    timezone: 8,
  },
  {
    name: "澳门",
    region: "澳门",
    longitude: 113.54,
    latitude: 22.2,
    timezone: 8,
  },
  {
    name: "台北",
    region: "台湾",
    longitude: 121.57,
    latitude: 25.04,
    timezone: 8,
  },
  {
    name: "新加坡",
    region: "海外",
    longitude: 103.82,
    latitude: 1.35,
    timezone: 8,
  },
  {
    name: "东京",
    region: "海外",
    longitude: 139.69,
    latitude: 35.68,
    timezone: 9,
  },
  {
    name: "首尔",
    region: "海外",
    longitude: 126.98,
    latitude: 37.57,
    timezone: 9,
  },
  {
    name: "伦敦",
    region: "海外",
    longitude: -0.12,
    latitude: 51.51,
    timezone: 0,
  },
  {
    name: "巴黎",
    region: "海外",
    longitude: 2.35,
    latitude: 48.86,
    timezone: 1,
  },
  {
    name: "纽约",
    region: "海外",
    longitude: -74.01,
    latitude: 40.71,
    timezone: -5,
  },
  {
    name: "洛杉矶",
    region: "海外",
    longitude: -118.24,
    latitude: 34.05,
    timezone: -8,
  },
  {
    name: "温哥华",
    region: "海外",
    longitude: -123.12,
    latitude: 49.28,
    timezone: -8,
  },
  {
    name: "悉尼",
    region: "海外",
    longitude: 151.21,
    latitude: -33.87,
    timezone: 10,
  },
];

export type RegionCity = {
  code: string;
  name: string;
  longitude: number;
  latitude: number;
};
export type Province = { code: string; name: string; cities: RegionCity[] };
export const PROVINCES: Province[] = regions;
